// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `PollingChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joey.ice.chat.slice.polling;

public interface _PollingChatSessionOperations
{
    String[] getInitialUsers(Ice.Current __current);

    ChatRoomEvent[] getUpdates(Ice.Current __current);

    long send(String message, Ice.Current __current)
        throws com.joey.ice.chat.slice.common.InvalidMessageException;

    void destroy(Ice.Current __current);
}
