// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `PollingChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joey.ice.chat.slice.polling;

public interface PollingChatSessionPrx extends Ice.ObjectPrx
{
    public String[] getInitialUsers();

    public String[] getInitialUsers(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInitialUsers();

    public Ice.AsyncResult begin_getInitialUsers(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getInitialUsers(Ice.Callback __cb);

    public Ice.AsyncResult begin_getInitialUsers(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getInitialUsers(Callback_PollingChatSession_getInitialUsers __cb);

    public Ice.AsyncResult begin_getInitialUsers(java.util.Map<String, String> __ctx, Callback_PollingChatSession_getInitialUsers __cb);

    public Ice.AsyncResult begin_getInitialUsers(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInitialUsers(IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getInitialUsers(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getInitialUsers(java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public String[] end_getInitialUsers(Ice.AsyncResult __result);

    public ChatRoomEvent[] getUpdates();

    public ChatRoomEvent[] getUpdates(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getUpdates();

    public Ice.AsyncResult begin_getUpdates(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getUpdates(Ice.Callback __cb);

    public Ice.AsyncResult begin_getUpdates(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getUpdates(Callback_PollingChatSession_getUpdates __cb);

    public Ice.AsyncResult begin_getUpdates(java.util.Map<String, String> __ctx, Callback_PollingChatSession_getUpdates __cb);

    public Ice.AsyncResult begin_getUpdates(IceInternal.Functional_GenericCallback1<ChatRoomEvent[]> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getUpdates(IceInternal.Functional_GenericCallback1<ChatRoomEvent[]> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getUpdates(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<ChatRoomEvent[]> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getUpdates(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<ChatRoomEvent[]> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public ChatRoomEvent[] end_getUpdates(Ice.AsyncResult __result);

    public long send(String message)
        throws com.joey.ice.chat.slice.common.InvalidMessageException;

    public long send(String message, java.util.Map<String, String> __ctx)
        throws com.joey.ice.chat.slice.common.InvalidMessageException;

    public Ice.AsyncResult begin_send(String message);

    public Ice.AsyncResult begin_send(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_send(String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_send(String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_send(String message, Callback_PollingChatSession_send __cb);

    public Ice.AsyncResult begin_send(String message, java.util.Map<String, String> __ctx, Callback_PollingChatSession_send __cb);

    public Ice.AsyncResult begin_send(String message, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_send(String message, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_send(String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_send(String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.UserException> __userExceptionCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public long end_send(Ice.AsyncResult __result)
        throws com.joey.ice.chat.slice.common.InvalidMessageException;

    public void destroy();

    public void destroy(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_destroy();

    public Ice.AsyncResult begin_destroy(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_destroy(Ice.Callback __cb);

    public Ice.AsyncResult begin_destroy(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_destroy(Callback_PollingChatSession_destroy __cb);

    public Ice.AsyncResult begin_destroy(java.util.Map<String, String> __ctx, Callback_PollingChatSession_destroy __cb);

    public Ice.AsyncResult begin_destroy(IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_destroy(IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_destroy(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_destroy(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_destroy(Ice.AsyncResult __result);
}
