// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `PushChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joey.ice.chat.slice.push;

public interface _ChatSessionOperationsNC extends Glacier2._SessionOperationsNC
{
    void setCallback(ChatRoomCallbackPrx cb);

    long send(String message)
        throws com.joey.ice.chat.slice.common.InvalidMessageException;
}
