// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `PushChat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.joey.ice.chat.slice.push;

public interface ChatRoomCallbackPrx extends Ice.ObjectPrx
{
    public void init(String[] users);

    public void init(String[] users, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_init(String[] users);

    public Ice.AsyncResult begin_init(String[] users, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_init(String[] users, Ice.Callback __cb);

    public Ice.AsyncResult begin_init(String[] users, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_init(String[] users, Callback_ChatRoomCallback_init __cb);

    public Ice.AsyncResult begin_init(String[] users, java.util.Map<String, String> __ctx, Callback_ChatRoomCallback_init __cb);

    public Ice.AsyncResult begin_init(String[] users, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_init(String[] users, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_init(String[] users, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_init(String[] users, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_init(Ice.AsyncResult __result);

    public void join(long timestamp, String name);

    public void join(long timestamp, String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_join(long timestamp, String name);

    public Ice.AsyncResult begin_join(long timestamp, String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_join(long timestamp, String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_join(long timestamp, String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_join(long timestamp, String name, Callback_ChatRoomCallback_join __cb);

    public Ice.AsyncResult begin_join(long timestamp, String name, java.util.Map<String, String> __ctx, Callback_ChatRoomCallback_join __cb);

    public Ice.AsyncResult begin_join(long timestamp, 
                                      String name, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_join(long timestamp, 
                                      String name, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_join(long timestamp, 
                                      String name, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_join(long timestamp, 
                                      String name, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_join(Ice.AsyncResult __result);

    public void leave(long timestamp, String name);

    public void leave(long timestamp, String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_leave(long timestamp, String name);

    public Ice.AsyncResult begin_leave(long timestamp, String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_leave(long timestamp, String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_leave(long timestamp, String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_leave(long timestamp, String name, Callback_ChatRoomCallback_leave __cb);

    public Ice.AsyncResult begin_leave(long timestamp, String name, java.util.Map<String, String> __ctx, Callback_ChatRoomCallback_leave __cb);

    public Ice.AsyncResult begin_leave(long timestamp, 
                                       String name, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_leave(long timestamp, 
                                       String name, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_leave(long timestamp, 
                                       String name, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_leave(long timestamp, 
                                       String name, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_leave(Ice.AsyncResult __result);

    public void send(long timestamp, String name, String message);

    public void send(long timestamp, String name, String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message, Callback_ChatRoomCallback_send __cb);

    public Ice.AsyncResult begin_send(long timestamp, String name, String message, java.util.Map<String, String> __ctx, Callback_ChatRoomCallback_send __cb);

    public Ice.AsyncResult begin_send(long timestamp, 
                                      String name, 
                                      String message, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_send(long timestamp, 
                                      String name, 
                                      String message, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_send(long timestamp, 
                                      String name, 
                                      String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_send(long timestamp, 
                                      String name, 
                                      String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_send(Ice.AsyncResult __result);
}
